### ISSUE TITLE
Unable to run sample app

### ISSUE THREAD

**Issue by RichPlannuh** [trayio/embedded-edition-sample-app#16]
Hi, I follow the instructions. Got a high severity warning at npm install but audit fix says the change is breaking so I left it alone. I run setup.sh, enter my master token and the app appears to launch spawning an open page in Chrome. But the app has already crashed. From the app:
Compiled with warnings.

./src/views/Demo.js
  Line 2:    'View' is defined but never used                                                  no-unused-vars
  Line 3:    'Error' is defined but never used                                                 no-unused-vars
  Line 108:  Links must not point to "#". Use a more descriptive href or use a button instead  jsx-a11y/href-no-hash
  Line 157:  'styles' is assigned a value but never used                                       no-unused-vars
  Line 179:  Links must not point to "#". Use a more descriptive href or use a button instead  jsx-a11y/href-no-hash
  Line 180:  Links must not point to "#". Use a more descriptive href or use a button instead  jsx-a11y/href-no-hash
  Line 186:  Links must not point to "#". Use a more descriptive href or use a button instead  jsx-a11y/href-no-hash

./src/components/auth/Auth.js
  Line 2:  'withRouter' is defined but never used  no-unused-vars

./src/components/Loading.js
  Line 5:  Useless constructor  no-useless-constructor

./src/components/View.js
  Line 7:  'theme' is assigned a value but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

internal/buffer.js:788
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:788:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:144:17)
    at Stream.<anonymous> (/Users/richsadowsky/source/plannuh/integrations/embedded-edition-sample-app/node_modules/handle-thing/lib/handle.js:120:12)
    at Stream.emit (events.js:202:15)
    at endReadableNT (/Users/richsadowsky/source/plannuh/integrations/embedded-edition-sample-app/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oemreactsample@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oemreactsample@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richsadowsky/.npm/_logs/2019-02-06T05_18_23_972Z-debug.log

Killing processes on port 3000 and 3001
Processes successfully killed
Terminated: 15

**Comment by ZeRego** [comment]
Hi @RichPlannuh 

Can you post the node version you are using ?
We recommend using LTS versions for node ( latests is v10.15.1 ) since they are more stable.

Thank you

**Comment by aychtang** [comment]
As discussed on slack we are only supporting current LTS version. Thanks for letting us know about audit issues - we will look into upgrading packages soon.
